apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-survey
  labels:
    app: common-survey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-survey
  template:
    metadata:
      labels:
        app: common-survey
    spec:
      containers:
        - name: common-survey
          image: registry.grupo.corp/common-survey-api:latest
          imagePullPolicy: "Always"
          env:
            - name: apiUrl
              value: "https://api.com/common/survey"
            - name: DB_CONNSTR
              value: "mongodb://mongodb:RbmpM3fqZvsFJ1cNtx6Gvwmstg==@mongodb.documents.com:10255/survey?ssl=true&replicaSet=globaldb"
      nodeSelector:
        infrastructure: cloud

---
apiVersion: v1
kind: Service
metadata:
  name: common-survey
  namespace: default
  labels:
    app: common-survey
spec:
  type: ClusterIP
  selector:
    app: common-survey
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress-survey
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: api.com
      http:
        paths:
          - path: /common/survey/?(.*)
            backend:
              serviceName: common-survey
              servicePort: 80
    - host: api.grupo.corp
      http:
        paths:
          - path: /common/survey/?(.*)
            backend:
              serviceName: common-survey
              servicePort: 80
